import torch

a = torch.tensor([2., 3.2])
b = torch.empty(2, 3)
print(a)
print(b)
x = torch.rand(5, 3)
print(x)
y = torch.zeros(5, 4, dtype=torch.long)
print(y)
x = x.view(-1, 5)
print(x)
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(x.grad_fn)
print(y.grad_fn)
z = y*y*3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)
print(torch.FloatTensor(1))
print(torch.tensor([1.2, 3]).type())
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).type())
